#!/usr/bin/env python3

import skilstak.colors as c
from random import randint

def pick():
    return randint(1,4)

def pick_colored():
    num = pick()
    if num == 1:
        return c.red + '1'
    elif num == 2:
        return c.blue + '2'
    elif num == 3:
        return c.yellow + '3'
    elif num == 3:
        return c.green + '4'


    


if __name__ == '__main__':
    print(c.clear + c.blue + 'Welcome to the Simon program' + c.x)
    print(pick_colored())


